In [1]:
#Import Required Libraries
import pandas as pd
import numpy as np

In [2]:
#Load Dataset Using Pandas

df = pd.read_csv("/content/Retail_Dataset_Cleaned 5.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [3]:
# Display First Five Records
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6,57,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4,99,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4,101,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5,79,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2,110,1,2022,Q1,Spring

In [4]:
# Check Dataset Information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5146 entries, 0 to 5145
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5146 non-null   object
 1   Store_Name             5146 non-null   object
 2   Brand_Name             5146 non-null   object
 3   Store_Type             5146 non-null   object
 4   City                   5146 non-null   object
 5   City_Tier              5146 non-null   object
 6   Product_Name           5146 non-null   object
 7   Category               5146 non-null   object
 8   Sub_Category           5146 non-null   object
 9   Product_Stage          5146 non-null   object
 10  Quantity_Available     5146 non-null   int64
 11  Units_Sold             5146 non-null   int64
 12  Unit_Price             5146 non-null   int64
 13  Cost_Price             5146 non-null   int64
 14  Revenue                5146 non-null   int64
 15  Profit_Margin          5146 non-null   float64
 16  Average_Order_Value    5146 non-null   int64
 17  Inventory_Turnover     5146 non-null   float64
 18  Days_of_Stock          5146 non-null   int64
 19  Customer_Segment       5146 non-null   object
 20  Sales_Channel          5146 non-null   object
 21  Payment_Method         5146 non-null   object
 22  Supplier               5146 non-null   object
 23  Supplier_Rating        5146 non-null   object
 24  Promotion_Type         5146 non-null   object
 25  Promotion_Impact       5146 non-null   float64
 26  Max_Discount_Offered   5146 non-null   int64
 27  Return_Rate            5146 non-null   float64
 28  Return_Reason          5146 non-null   object
 29  Customer_Satisfaction  5146 non-null   float64
 30  Online_Rating          5146 non-null   float64
 31  Review_Count           5146 non-null   int64
 32  Sales_Rep_Experience   5146 non-null   int64
 33  Sales_Rep_Rating       5146 non-null   float64
 34  Market_Share           5146 non-null   float64
 35  Competition_Level      5146 non-null   object
 36  Competitor_Count       5146 non-null   int64
 37  Brand_Loyalty          5146 non-null   float64
 38  Brand_Awareness        5146 non-null   float64
 39  Price_Competitiveness  5146 non-null   object
 40  Weather_Impact         5146 non-null   object
 41  Delivery_Time          5146 non-null   int64
 42  Shipping_Cost          5146 non-null   int64
 43  Month                  5146 non-null   int64
 44  Year                   5146 non-null   int64
 45  Quarter                5146 non-null   object
 46  Season                 5146 non-null   object
dtypes: float64(10), int64(15), object(22)
memory usage: 1.8+ MB

In [5]:
# Create Profit Amount Column
# Formula - Profit Amount = Revenue × Profit Margin / 100

df["Profit_Amount"] = (
    df["Revenue"] *
    df["Profit_Margin"] / 100
)

df[["Revenue",
    "Profit_Margin",
    "Profit_Amount"]].sample(5)

      Revenue  Profit_Margin  Profit_Amount
3293    21808          15.96      3480.5568
1936    36801          18.91      6959.0691
3898    42000          28.00     11760.0000
4022   309180          15.49     47891.9820
4391  2069550          29.26    605550.3300

In [6]:
# Create Stock Difference Column

df["Stock_Difference"] = (
    df["Quantity_Available"] -
    df["Units_Sold"]
)

df[["Quantity_Available",
    "Units_Sold",
    "Stock_Difference"]].sample(5)

      Quantity_Available  Units_Sold  Stock_Difference
912                   84          42                42
3229                 120          62                58
1559                 168          75                93
1818                 226          86               140
2815                  48          25                23

In [7]:
# Create Inventory Status Column

df["Inventory_Status"] = np.where(
    df["Quantity_Available"] < 100,
    "Low Stock",
    np.where(
        df["Quantity_Available"] <= 200,
        "Medium Stock",
        "High Stock"
    )
)

df[["Quantity_Available",
    "Inventory_Status"]].sample(5)

      Quantity_Available Inventory_Status
3717                 193     Medium Stock
2781                 195     Medium Stock
3014                 149     Medium Stock
1610                 265       High Stock
862                  118     Medium Stock

In [8]:
# Create Revenue Per Unit Column

df["Revenue_Per_Unit"] = (
    df["Revenue"] /
    df["Units_Sold"]
)

df[["Revenue",
    "Units_Sold",
    "Revenue_Per_Unit"]].sample(5)

      Revenue  Units_Sold  Revenue_Per_Unit
1461    20216         133             152.0
4540  2347200          45           52160.0
4756     3060          85              36.0
1743   312116          28           11147.0
4659  2748192          48           57254.0

In [9]:
# Verify Newly Created Columns

print(df[[
    "Profit_Amount",
    "Stock_Difference",
    "Inventory_Status",
    "Revenue_Per_Unit"
]].head())

   Profit_Amount  Stock_Difference Inventory_Status  Revenue_Per_Unit
0      1584.0480               101     Medium Stock             305.0
1       490.0455               100     Medium Stock              47.0
2     13175.1240               184       High Stock            2140.0
3     14080.1628               141     Medium Stock            3534.0
4    398237.3460               128     Medium Stock           50676.0

In [10]:
# Task 2: Transform Data
# Transform Revenue into Revenue Category

df["Revenue_Category"] = np.where(
    df["Revenue"] < 5000,
    "Low Revenue",
    np.where(df["Revenue"] < 10000,
        "Medium Revenue",
        "High Revenue"))

df[["Revenue", "Revenue_Category"]].head()

   Revenue Revenue_Category
0     7320   Medium Revenue
1     1645      Low Revenue
2    66340     High Revenue
3    77748     High Revenue
4  1976364     High Revenue

In [11]:
# Transform Customer Satisfaction Ratings

df["Customer_Feedback"] = np.where(
    df["Customer_Satisfaction"] >= 4,
    "Satisfied",
    "Needs Improvement")

df[["Customer_Satisfaction",
    "Customer_Feedback"]].head()

   Customer_Satisfaction  Customer_Feedback
0                    4.0          Satisfied
1                    3.9  Needs Improvement
2                    4.3          Satisfied
3                    4.4          Satisfied
4                    3.9  Needs Improvement

In [12]:
# Create Discount Category

df["Discount_Category"] = np.where(
    df["Max_Discount_Offered"] < 10,
    "Low Discount",
    np.where(df["Max_Discount_Offered"] < 20,
        "Medium Discount",
        "High Discount"))

df[["Max_Discount_Offered", "Discount_Category"]].sample(5)

      Max_Discount_Offered Discount_Category
2987                     8      Low Discount
3821                     0      Low Discount
2138                    19   Medium Discount
912                     24     High Discount
2443                     7      Low Discount

In [13]:
# Create Delivery Speed Category

df["Delivery_Speed"] = np.where(
    df["Delivery_Time"] <= 5,
    "Fast Delivery",
    "Standard Delivery")

df[[
    "Delivery_Time",
    "Delivery_Speed"]].head()

   Delivery_Time     Delivery_Speed
0              6  Standard Delivery
1              4      Fast Delivery
2              4      Fast Delivery
3              5      Fast Delivery
4              2      Fast Delivery

In [14]:
# Display Transformed Columns

print(df[[
    "Revenue_Category",
    "Customer_Feedback",
    "Discount_Category",
    "Delivery_Speed"
]].head())

  Revenue_Category  Customer_Feedback Discount_Category     Delivery_Speed
0   Medium Revenue          Satisfied      Low Discount  Standard Delivery
1      Low Revenue  Needs Improvement     High Discount      Fast Delivery
2     High Revenue          Satisfied     High Discount      Fast Delivery
3     High Revenue          Satisfied     High Discount      Fast Delivery
4     High Revenue  Needs Improvement     High Discount      Fast Delivery

In [15]:
# Check Dataset Information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5146 entries, 0 to 5145
Data columns (total 55 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5146 non-null   object
 1   Store_Name             5146 non-null   object
 2   Brand_Name             5146 non-null   object
 3   Store_Type             5146 non-null   object
 4   City                   5146 non-null   object
 5   City_Tier              5146 non-null   object
 6   Product_Name           5146 non-null   object
 7   Category               5146 non-null   object
 8   Sub_Category           5146 non-null   object
 9   Product_Stage          5146 non-null   object
 10  Quantity_Available     5146 non-null   int64
 11  Units_Sold             5146 non-null   int64
 12  Unit_Price             5146 non-null   int64
 13  Cost_Price             5146 non-null   int64
 14  Revenue                5146 non-null   int64
 15  Profit_Margin          5146 non-null   float64
 16  Average_Order_Value    5146 non-null   int64
 17  Inventory_Turnover     5146 non-null   float64
 18  Days_of_Stock          5146 non-null   int64
 19  Customer_Segment       5146 non-null   object
 20  Sales_Channel          5146 non-null   object
 21  Payment_Method         5146 non-null   object
 22  Supplier               5146 non-null   object
 23  Supplier_Rating        5146 non-null   object
 24  Promotion_Type         5146 non-null   object
 25  Promotion_Impact       5146 non-null   float64
 26  Max_Discount_Offered   5146 non-null   int64
 27  Return_Rate            5146 non-null   float64
 28  Return_Reason          5146 non-null   object
 29  Customer_Satisfaction  5146 non-null   float64
 30  Online_Rating          5146 non-null   float64
 31  Review_Count           5146 non-null   int64
 32  Sales_Rep_Experience   5146 non-null   int64
 33  Sales_Rep_Rating       5146 non-null   float64
 34  Market_Share           5146 non-null   float64
 35  Competition_Level      5146 non-null   object
 36  Competitor_Count       5146 non-null   int64
 37  Brand_Loyalty          5146 non-null   float64
 38  Brand_Awareness        5146 non-null   float64
 39  Price_Competitiveness  5146 non-null   object
 40  Weather_Impact         5146 non-null   object
 41  Delivery_Time          5146 non-null   int64
 42  Shipping_Cost          5146 non-null   int64
 43  Month                  5146 non-null   int64
 44  Year                   5146 non-null   int64
 45  Quarter                5146 non-null   object
 46  Season                 5146 non-null   object
 47  Profit_Amount          5146 non-null   float64
 48  Stock_Difference       5146 non-null   int64
 49  Inventory_Status       5146 non-null   object
 50  Revenue_Per_Unit       5146 non-null   float64
 51  Revenue_Category       5146 non-null   object
 52  Customer_Feedback      5146 non-null   object
 53  Discount_Category      5146 non-null   object
 54  Delivery_Speed         5146 non-null   object
dtypes: float64(12), int64(16), object(27)
memory usage: 2.2+ MB